set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
setw -g mode-keys vi
set -g history-limit 100000
set -g default-terminal "tmux-256color"
set -as terminal-features ',xterm-256color:RGB'

bind r source-file ~/.tmux.conf \; display-message 'tmux.conf reloaded'
bind v split-window -h -c '#{pane_current_path}'
bind s split-window -v -c '#{pane_current_path}'
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel \
  'command -v pbcopy >/dev/null && pbcopy || command -v wl-copy >/dev/null && wl-copy || xclip -selection clipboard'

source-file -q ~/.config/tmux/local.conf
